### PR TITLE
create basic ui

### PR DESCRIPTION
**Pull request by Tobby8629**
create basic UI using the command prompt
- create a menu section and instructions on how to naviagate the menu section
- create an entry section in the main.rb file
-  All method for the functionality of the menu in the app.rb file
- menu section include
   - list all books
   - list all people
   - create a person
   - create a book
   - create a rental
   - list all rentals for a given person id
   - Exit

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @Tobby8629, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Your app runs and performs as expected. Well done!
- You used the recommended readme template

## Required Changes ♻️
_Check the comments under the review._
- Make changes to your readme file. Give explicit command for getting started. I had to run `ruby main.rb` to get started but this was not in the readme instructions. Please make that change.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It's a good idea to properly format content in the readme to improve readability. For example, instead of "git clone", you could do `git clone`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BregornOriginal — APPROVED** [review]
### Hi @Tobby8629 

### Your project is complete!  There is nothing else to say other than... it's time to merge it 

### Congratulations! 

approve-applause

### Highlights

✔️ Linters are passing
✔️ Good commit history
✔️ README looks professional

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Comment by Tobby8629** [comment]
@afanimartin @BregornOriginal  I appreciate the good review and correction

**Comment by Tobby8629** [comment]
@afanimartin  is there a way you can put me through achieving the optional suggestion, I have tried working on it but i did not get the background effect of the git clone

**Pull request merged**
